<?php

namespace App\Http\Resources;

use App\Context\StatusTrips;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;
use OpenApi\Attributes as OA;

#[OA\Schema(
    schema: 'TripEndpoint',
    description: 'An origin or destination location point — either a logistics company or a port terminal.',
    properties: [
        new OA\Property(property: 'type', type: 'string', enum: ['company', 'port'], example: 'company', description: 'Location type: company (industrial facility/warehouse) or port (maritime terminal)'),
        new OA\Property(property: 'id', type: 'integer', example: 1, description: 'Unique identifier of the company or port'),
        new OA\Property(property: 'name', type: 'string', example: 'Company A Logistics', description: 'Human-readable location name'),
        new OA\Property(property: 'latitude', type: 'number', format: 'float', example: 1.1234567, description: 'Latitude coordinate. Used by frontend TomTom Maps SDK to render map route.'),
        new OA\Property(property: 'longitude', type: 'number', format: 'float', example: 104.0123456, description: 'Longitude coordinate. Used by frontend TomTom Maps SDK to render map route.'),
    ],
    type: 'object'
)]
#[OA\Schema(
    schema: 'Trip',
    description: 'Complete Trip resource model representing domestic or cross-border logistics shipments',
    properties: [
        new OA\Property(property: 'id', type: 'integer', example: 1, description: 'Unique identifier of the trip'),
        new OA\Property(property: 'origin', ref: '#/components/schemas/TripEndpoint', description: 'Origin location endpoint (Company or Port)'),
        new OA\Property(property: 'destination', ref: '#/components/schemas/TripEndpoint', description: 'Destination location endpoint (Company or Port where the truck drives to)'),
        new OA\Property(property: 'ship_destination_port', ref: '#/components/schemas/TripEndpoint', nullable: true, description: 'Cross-border only: Pelabuhan Singapura tujuan KAPAL (null for domestic trips)'),
        new OA\Property(property: 'truck_id', type: 'integer', nullable: true, example: 1, description: 'Assigned truck ID (null in draft status)'),
        new OA\Property(property: 'driver_id', type: 'integer', nullable: true, example: 2, description: 'Assigned driver ID (null in draft status)'),
        new OA\Property(property: 'ship_ref_id', type: 'string', nullable: true, example: '563012340', description: 'MMSI/IMO number of the vessel for cross-border tracking'),
        new OA\Property(
            property: 'recommended_slots',
            type: 'array',
            nullable: true,
            description: '3 recommended departure time slots with scores and penalty breakdown (generated by POST /trips/{id}/recommend)',
            items: new OA\Items(
                properties: [
                    new OA\Property(property: 'departure_at', type: 'string', format: 'date-time', example: '2026-08-15T06:00:00Z'),
                    new OA\Property(property: 'score', type: 'number', format: 'float', example: 92.5),
                    new OA\Property(property: 'reason', type: 'string', example: '06:00 — lalu lintas lancar, estimasi tiba 06:45'),
                    new OA\Property(property: 'travel_time_seconds', type: 'integer', example: 2700),
                    new OA\Property(property: 'breakdown', type: 'object', properties: [
                        new OA\Property(property: 'traffic_penalty', type: 'number', example: 0),
                        new OA\Property(property: 'delay_penalty', type: 'number', example: 2.5),
                        new OA\Property(property: 'night_penalty', type: 'number', example: 0),
                    ]),
                ]
            )
        ),
        new OA\Property(property: 'chosen_departure_at', type: 'string', format: 'date-time', nullable: true, example: '2026-08-15T06:00:00Z', description: 'Confirmed departure timestamp chosen by Admin'),
        new OA\Property(
            property: 'status',
            type: 'string',
            enum: [
                StatusTrips::DRAFT,
                StatusTrips::ASSIGNED,
                StatusTrips::IN_TRANSIT_ORIGIN,
                StatusTrips::AT_ORIGIN_PORT,
                StatusTrips::ON_SHIP,
                StatusTrips::AT_DESTINATION_PORT,
                StatusTrips::IN_TRANSIT_DESTINATION,
                StatusTrips::ARRIVED,
                StatusTrips::COMPLETED,
                StatusTrips::CANCELLED,
            ],
            example: StatusTrips::DRAFT,
            description: 'Trip lifecycle state machine status: draft -> assigned -> in_transit_origin -> at_origin_port -> on_ship -> at_destination_port -> completed'
        ),
        new OA\Property(property: 'distance_km', type: 'number', format: 'float', nullable: true, example: 15.4, description: 'Route distance in km computed by TomTom Traffic API'),
        new OA\Property(property: 'estimated_co2_kg', type: 'number', format: 'float', nullable: true, example: 3.85, description: 'Estimated carbon emissions in kg (distance_km x emission_factor)'),
        new OA\Property(property: 'estimated_duration_min', type: 'integer', nullable: true, example: 25, description: 'Estimated travel time in minutes computed by TomTom Traffic API'),
        new OA\Property(property: 'actual_departure_at', type: 'string', format: 'date-time', nullable: true, description: 'Actual departure timestamp when driver starts journey'),
        new OA\Property(property: 'actual_arrival_at', type: 'string', format: 'date-time', nullable: true, description: 'Actual arrival timestamp when cargo reaches destination'),
        new OA\Property(property: 'truck_returned_at', type: 'string', format: 'date-time', nullable: true, description: 'Cross-border only: timestamp when Company A truck returned back to origin base'),
        new OA\Property(property: 'created_by', type: 'integer', example: 1, description: 'User ID of the Admin who created the trip'),
        new OA\Property(property: 'created_at', type: 'string', format: 'date-time', description: 'Creation timestamp'),
        new OA\Property(property: 'updated_at', type: 'string', format: 'date-time', description: 'Last update timestamp'),
    ],
    type: 'object'
)]
class TripResource extends JsonResource
{
    /**
     * @return array<string, mixed>
     */
    public function toArray(Request $request): array
    {
        return [
            'id' => $this->id,
            'origin' => $this->when(
                $this->origin_company_id || $this->origin_port_id,
                fn () => $this->origin_company_id
                    ? ['type' => 'company', 'id' => $this->origin_company_id, 'name' => $this->originCompany?->name, 'latitude' => (float) $this->originCompany?->latitude, 'longitude' => (float) $this->originCompany?->longitude]
                    : ['type' => 'port', 'id' => $this->origin_port_id, 'name' => $this->originPort?->name, 'latitude' => (float) $this->originPort?->latitude, 'longitude' => (float) $this->originPort?->longitude]
            ),
            'destination' => $this->when(
                $this->destination_company_id || $this->destination_port_id,
                fn () => $this->destination_company_id
                    ? ['type' => 'company', 'id' => $this->destination_company_id, 'name' => $this->destinationCompany?->name, 'latitude' => (float) $this->destinationCompany?->latitude, 'longitude' => (float) $this->destinationCompany?->longitude]
                    : ['type' => 'port', 'id' => $this->destination_port_id, 'name' => $this->destinationPort?->name, 'latitude' => (float) $this->destinationPort?->latitude, 'longitude' => (float) $this->destinationPort?->longitude]
            ),
            'ship_destination_port' => $this->when(
                (bool) $this->ship_destination_port_id,
                fn () => ['id' => $this->ship_destination_port_id, 'name' => $this->shipDestinationPort?->name, 'latitude' => (float) $this->shipDestinationPort?->latitude, 'longitude' => (float) $this->shipDestinationPort?->longitude]
            ),
            'truck_id' => $this->truck_id,
            'driver_id' => $this->driver_id,
            'ship_ref_id' => $this->ship_ref_id,
            'recommended_slots' => $this->recommended_slots,
            'chosen_departure_at' => $this->chosen_departure_at,
            'status' => $this->status,
            'distance_km' => $this->distance_km,
            'estimated_co2_kg' => $this->estimated_co2_kg,
            'estimated_duration_min' => $this->estimated_duration_min,
            'actual_departure_at' => $this->actual_departure_at,
            'actual_arrival_at' => $this->actual_arrival_at,
            'truck_returned_at' => $this->truck_returned_at,
            'created_by' => $this->created_by,
            'created_at' => $this->created_at,
            'updated_at' => $this->updated_at,
        ];
    }
}
